### ISSUE TITLE
Add `Button` subclass that directly enters the text

### ISSUE THREAD

**Issue by ByteHamster** [mr-kenhoff/qalculate-android#15]
Currently, there is a lot of mapping going on. Each button is created in XML and then gets a line of Kotlin that actually types in the content. With more complex screens that have far more buttons, that Kotlin part will get a bit ugly.

My proposal would be to create a subclass of `Button` that automatically adds its text to the main equation. I suggest sending the button press events using EventBus. The subclass could get its own xml attributes, for example when the typed text does not match the button text (sqrt vs √, division vs /, ...). Then we do not need any Kotlin for adding new buttons, which means that screens can be defined entirely in XML.

**Comment by mr-kenhoff** [comment]
Nice idea! I was also thinking about user-customizable screens. In this case, there needs to be some kind of button library, and a layout editor. However, I do not know if many users would actually use such a feature. A few well designed screens for different applications / complexities might come in more handy...

In general, the problem of packing the insane capabilities of Qalculate in a mobile form factor, without becoming bloated, is still an open question to me.

When it comes to the buttons, I thought about some kind of "swipe buttons", as there are for example used in the Unexpected Keyboard: https://github.com/Julow/Unexpected-Keyboard

Anyhow, I totally agree that there needs to be a clean way of specifying button layouts

**Comment by ByteHamster** [comment]
I copied a few things to individual issues, so it is easier to discuss. About the button subclass click handling: Are you fine with using [EventBus](https://github.com/greenrobot/EventBus)? We are using it in AntennaPod and I find it very convenient.

Is there a Kotlin built-in alternative (I pretty much don't know any Kotlin)? Something like [this](https://medium.com/tech-takeaways/how-to-implement-the-event-bus-pattern-with-kotlin-sharedflow-in-your-android-app-768529828607) sounds like it would need a lot of manual work when wanting to support more features.
