### ISSUE TITLE
Implement unit conversion using "to" syntax

### ISSUE THREAD

**Issue by mr-kenhoff** [mr-kenhoff/qalculate-android#28]

**Comment by ByteHamster** [comment]
This already works for me 🤔 

![Screenshot_20220405-205852_Qalculate!](https://user-images.githubusercontent.com/5811634/161829687-6de4a311-d172-4bc9-a619-aa57d9af9b46.png)

**Comment by mr-kenhoff** [comment]
You are totally right. Dont know how I could miss that.
Closed...
