### ISSUE TITLE
Support units

### ISSUE THREAD

**Issue by ByteHamster** [mr-kenhoff/qalculate-android#8]
Currently, units are interpreted as variables. `2m^2` should display `2m²`, not `2'm'^2`.

**Comment by mr-kenhoff** [comment]
Yeaah, this is pretty unfortunate :D This is likely because the global definitions are currently not loaded.

**Comment by mr-kenhoff** [comment]
Fixed :+1: However, in order for that to work, you need to recompile the libqalculate library
